api_platform:
    title: Nubit Admin API
    version: 1.0.0
    defaults:
        stateless: true
        pagination_client_items_per_page: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
