framework:
    messenger:
        failure_transport: failed

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: '%env(MESSENGER_FAILED_TRANSPORT_DSN)%'
            sync: 'sync://'

        routing:
            'Nubit\AdminBundle\Analytics\Message\DeliverAnalyticsOutbox': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
                failed: 'in-memory://'
