<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260612111723 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE nubit_audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, resource VARCHAR(100) NOT NULL, resource_id VARCHAR(64) NOT NULL, action VARCHAR(10) NOT NULL, changes JSON NOT NULL, username VARCHAR(180) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_NUBIT_AUDIT_RESOURCE ON nubit_audit_log (resource, resource_id, created_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE nubit_audit_log');
    }
}
