<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260821212746 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_APP_USER_EMAIL ON app_user (email)');
        $this->addSql('CREATE TABLE nubit_refresh_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jti VARCHAR(64) NOT NULL, token_hash VARCHAR(64) NOT NULL, user_identifier VARCHAR(180) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_NUBIT_REFRESH_TOKEN_USER ON nubit_refresh_token (user_identifier)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_NUBIT_REFRESH_TOKEN_JTI ON nubit_refresh_token (jti)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_NUBIT_REFRESH_TOKEN_HASH ON nubit_refresh_token (token_hash)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, sku VARCHAR(64) DEFAULT NULL, price NUMERIC(12, 2) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE nubit_refresh_token');
        $this->addSql('DROP TABLE product');
    }
}
