<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260617120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Sales documents master-detail tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE sales_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(32) NOT NULL, status VARCHAR(16) NOT NULL, total NUMERIC(12, 2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE sales_document_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity NUMERIC(12, 2) NOT NULL, unit_price NUMERIC(12, 2) NOT NULL, line_total NUMERIC(12, 2) NOT NULL, document_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_SALES_DOCUMENT_LINE_DOCUMENT ON sales_document_line (document_id)');
        $this->addSql('CREATE INDEX IDX_SALES_DOCUMENT_LINE_PRODUCT ON sales_document_line (product_id)');
        $this->addSql('ALTER TABLE sales_document_line ADD CONSTRAINT FK_SALES_DOCUMENT_LINE_DOCUMENT FOREIGN KEY (document_id) REFERENCES sales_document (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sales_document_line ADD CONSTRAINT FK_SALES_DOCUMENT_LINE_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE sales_document_line DROP CONSTRAINT FK_SALES_DOCUMENT_LINE_PRODUCT');
        $this->addSql('ALTER TABLE sales_document_line DROP CONSTRAINT FK_SALES_DOCUMENT_LINE_DOCUMENT');
        $this->addSql('DROP TABLE sales_document_line');
        $this->addSql('DROP TABLE sales_document');
    }
}