<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260821205404 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_APP_USER_EMAIL ON app_user (email)');
        $this->addSql('CREATE TABLE nubit_refresh_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jti VARCHAR(64) NOT NULL, token_hash VARCHAR(64) NOT NULL, user_identifier VARCHAR(180) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_NUBIT_REFRESH_TOKEN_USER ON nubit_refresh_token (user_identifier)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_NUBIT_REFRESH_TOKEN_JTI ON nubit_refresh_token (jti)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_NUBIT_REFRESH_TOKEN_HASH ON nubit_refresh_token (token_hash)');
        $this->addSql('CREATE TABLE organization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, slug VARCHAR(80) NOT NULL, primary_domain VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ORGANIZATION_SLUG ON organization (slug)');
        $this->addSql('CREATE TABLE organization_membership (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(16) NOT NULL, role VARCHAR(16) NOT NULL, organization_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FA4406A32C8A3DE ON organization_membership (organization_id)');
        $this->addSql('CREATE INDEX IDX_6FA4406AA76ED395 ON organization_membership (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ORGANIZATION_MEMBERSHIP ON organization_membership (organization_id, user_id)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, sku VARCHAR(64) DEFAULT NULL, price NUMERIC(12, 2) NOT NULL, active BOOLEAN NOT NULL, tenant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE organization_membership ADD CONSTRAINT FK_6FA4406A32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE organization_membership ADD CONSTRAINT FK_6FA4406AA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE organization_membership DROP CONSTRAINT FK_6FA4406A32C8A3DE');
        $this->addSql('ALTER TABLE organization_membership DROP CONSTRAINT FK_6FA4406AA76ED395');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE nubit_refresh_token');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE organization_membership');
        $this->addSql('DROP TABLE product');
    }
}
