<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260711000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds SaaS organizations, active memberships, and tenant ownership columns.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE organization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, slug VARCHAR(80) NOT NULL, primary_domain VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ORGANIZATION_SLUG ON organization (slug)');
        $this->addSql("CREATE TABLE organization_membership (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, user_id INT NOT NULL, status VARCHAR(16) NOT NULL, role VARCHAR(16) NOT NULL DEFAULT 'member', PRIMARY KEY (id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ORGANIZATION_MEMBERSHIP ON organization_membership (organization_id, user_id)');
        $this->addSql('CREATE INDEX IDX_ORGANIZATION_MEMBERSHIP_ORGANIZATION ON organization_membership (organization_id)');
        $this->addSql('CREATE INDEX IDX_ORGANIZATION_MEMBERSHIP_USER ON organization_membership (user_id)');
        $this->addSql('ALTER TABLE organization_membership ADD CONSTRAINT FK_ORGANIZATION_MEMBERSHIP_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE organization_membership ADD CONSTRAINT FK_ORGANIZATION_MEMBERSHIP_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');

        foreach (['product', 'customer', 'sales_document', 'sales_document_line', 'invoice', 'invoice_line', 'nubit_media', 'nubit_audit_log'] as $table) {
            $this->addSql(sprintf('ALTER TABLE %s ADD tenant_id INT DEFAULT NULL', $table));
            $this->addSql(sprintf('CREATE INDEX IDX_%s_TENANT ON %s (tenant_id)', strtoupper($table), $table));
        }
    }

    public function down(Schema $schema): void
    {
        foreach (['product', 'customer', 'sales_document', 'sales_document_line', 'invoice', 'invoice_line', 'nubit_media', 'nubit_audit_log'] as $table) {
            $this->addSql(sprintf('DROP INDEX IDX_%s_TENANT', strtoupper($table)));
            $this->addSql(sprintf('ALTER TABLE %s DROP tenant_id', $table));
        }

        $this->addSql('ALTER TABLE organization_membership DROP CONSTRAINT FK_ORGANIZATION_MEMBERSHIP_ORGANIZATION');
        $this->addSql('ALTER TABLE organization_membership DROP CONSTRAINT FK_ORGANIZATION_MEMBERSHIP_USER');
        $this->addSql('DROP TABLE organization_membership');
        $this->addSql('DROP TABLE organization');
    }
}
