<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260626122949 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE invoice (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(32) NOT NULL, issued_at DATE NOT NULL, due_at DATE DEFAULT NULL, status VARCHAR(16) NOT NULL, subtotal NUMERIC(12, 2) NOT NULL, tax NUMERIC(12, 2) NOT NULL, total NUMERIC(12, 2) NOT NULL, notes TEXT DEFAULT NULL, customer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9065174496901F54 ON invoice (number)');
        $this->addSql('CREATE INDEX IDX_906517449395C3F3 ON invoice (customer_id)');
        $this->addSql('CREATE TABLE invoice_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity NUMERIC(12, 2) NOT NULL, unit_price NUMERIC(12, 2) NOT NULL, tax_rate NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, line_total NUMERIC(12, 2) NOT NULL, invoice_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D3D1D6932989F1FD ON invoice_line (invoice_id)');
        $this->addSql('CREATE INDEX IDX_D3D1D6934584665A ON invoice_line (product_id)');
        $this->addSql('CREATE TABLE nubit_sequence_counter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scope_key VARCHAR(190) NOT NULL, name VARCHAR(64) NOT NULL, next_value INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SEQUENCE_SCOPE_NAME ON nubit_sequence_counter (scope_key, name)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517449395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice_line ADD CONSTRAINT FK_D3D1D6932989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice_line ADD CONSTRAINT FK_D3D1D6934584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_customer_preferred_product RENAME TO IDX_81398E09888E7B73');
        $this->addSql('ALTER INDEX idx_sales_document_line_document RENAME TO IDX_B3864ED6C33F7837');
        $this->addSql('ALTER INDEX idx_sales_document_line_product RENAME TO IDX_B3864ED64584665A');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_906517449395C3F3');
        $this->addSql('ALTER TABLE invoice_line DROP CONSTRAINT FK_D3D1D6932989F1FD');
        $this->addSql('ALTER TABLE invoice_line DROP CONSTRAINT FK_D3D1D6934584665A');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE invoice_line');
        $this->addSql('DROP TABLE nubit_sequence_counter');
        $this->addSql('ALTER INDEX idx_81398e09888e7b73 RENAME TO idx_customer_preferred_product');
        $this->addSql('ALTER INDEX idx_b3864ed6c33f7837 RENAME TO idx_sales_document_line_document');
        $this->addSql('ALTER INDEX idx_b3864ed64584665a RENAME TO idx_sales_document_line_product');
    }
}
