<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260617140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Customer resource with segment enum and preferred product relation';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, email VARCHAR(180) NOT NULL, segment VARCHAR(16) NOT NULL, preferred_product_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CUSTOMER_PREFERRED_PRODUCT ON customer (preferred_product_id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_CUSTOMER_PREFERRED_PRODUCT FOREIGN KEY (preferred_product_id) REFERENCES product (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE customer DROP CONSTRAINT FK_CUSTOMER_PREFERRED_PRODUCT');
        $this->addSql('DROP TABLE customer');
    }
}